<?php
$title = 'Manage Designation';
$this->headTitle($title);
?>
<h1 class="page-title"><?php echo $this->escapeHtml($title); ?></h1>

<div class="page-bar">
  <ul class="page-breadcrumb">
    <li><i class="fa fa-home"></i><a href="/dashboard">Home</a><i class="fa fa-angle-right"></i></li>
    <li>Manage Designation</li>
  </ul>
</div>

<div class="io-search-filter row">
  <div class="col-xs-6 col-sm-6">
    <h3>Search</h3>
  </div>
  <div class="col-xs-6 col-sm-6 text-right"><a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Show / Hide</a></div>
</div>

<div class="io-filter-block panel-collapse collapse in" id="collapseOne">
	<div class="row">
	<?php 
		$form = $this->form;
		$form->setAttribute('action', $this->url('designation'));
		$form->prepare();
		echo $this->form()->openTag($form);
	?>
      
    <div class="col-xs-12 col-sm-4 col-md-2">
        <label>Search Term</label>
        <?php echo $this->formElement($form->get('desig_name')); ?>
        <!--<input type="text" class="form-control" id="" placeholder="Designation Name">-->
    </div>
    
    <div class="col-xs-12 col-sm-3 col-md-2">
        <label>Select Department</label>
        <?php echo $this->formElement($form->get('depts')); ?>
    </div>
    
    <div class="col-xs-12 col-sm-2 col-md-2">
      <label>&nbsp;</label>
      <div class="form-group">
        <?php //echo $this->formElement($form->get('submit')); ?>
        <button class="btn btn-io" type="submit">Search</button>
      </div>
    </div>
    
    <?php echo $this->form()->closeTag(); ?>
    
	</div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-12 text-right">
    <a href="<?php echo $this->url('designation', array('action' => 'add'));?>" class="btn btn-default">Add Designation</a>
  </div>
</div>

<div class="row mt-10">
  <div class="col-xs-12 col-sm-12">
    
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="text-center" width="10%">S. No.</th>
            <th width="30%">Designation</th>
            <th width="45%">Department</th>
            <th width="15%">Action</th>
          </tr>
        </thead>
        <tbody>
        <?php
        if($this->desigs) :
            $i=1;
            foreach ($this->desigs as $desig) :
        ?>
          <tr>
            <td class="text-center"><?php echo $i; ?></td>
            <td><?php echo $this->escapeHtml($desig->desig_name); ?></td>
            <td><?php echo $this->escapeHtml($desig->dept_name); ?></td>
            <td>
                <ul class="quick-links">
                    <li><a href="<?php echo $this->url('designation', array('action' => 'edit', 'desig_id' => $desig->desig_id)); ?>"><i class="fa fa-edit"></i>Edit</a></li>
                    <li><a href="<?php echo $this->url('designation', array('action' => 'delete', 'desig_id' => $desig->desig_id)); ?>"><i class="fa fa-trash-o"></i>Delete</a></li>
                </ul>
            </td>
          </tr>
        <?php
            $i++;
            endforeach;
		else : 
		?>
		  <tr>
            <td class="text-center" colspan="4">No result found...!!!</td>
          </tr>
		<?php endif;  ?>
        </tbody>
      </table>
    </div>
    
    <div class="pagination-wrap">
    <?php // add at the end of the file after the table
        echo $this->paginationControl(
            $this->desigs,
            'Sliding',
            array('paginator.phtml', 'Designation'), 
            array('route' => 'designation', 'query'=>'&desig_name='.$this->topic_name)
        );
        
    ?>
    </div>
  </div>
</div>
