<?php
// module/TopicManagement/view/topic-management/topic-management/add.phtml:

$title = 'Edit topic';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('topic', array('action' => 'edit', 'topic_id'     => $this->topic_id,)));
$form->setAttribute('class', "form-horizontal");
$form->setAttribute('role', "form");
$form->prepare();
?>
<?=$this->form()->openTag($form); ?>

 <div class="form-group">
    <label class="col-sm-2 control-label">Topic Name</label>
    <div class="col-sm-10">
        <?=$this->formRow($form->get('topic_name')) . PHP_EOL;?>      
    </div>
  </div>  

<div class="form-group">
    <label class="col-sm-2 control-label">Technologies</label>
    <div class="col-sm-10">
        <?=$this->formRow($form->get('technologies')) . PHP_EOL;?>      
    </div>
  </div> 


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <?=$this->formRow($form->get('submit')) . PHP_EOL;?>
    </div>
  </div>
<?=$this->formHidden($form->get('topic_id')); ?>
<!--<?=$this->formCollection($form);?> -->
<?=$this->form()->closeTag();?>
