<?php
$title = 'My Topic';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>



<p><a href="<?php
echo $this->url('topic', array(
    'action' => 'add'));
?>">Add new Topic</a></p>

<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('topic'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>
<table class="table">
    <tr>
        <th>
            Topic Name
        </th>
        <th>
            Topic Description    
        </th>
        <th>Action</th>
    </tr>
    <?php if($this->topics) : ?>
    <?php foreach ($this->topics as $topic) :    
    ?>
        <tr>
            <td><?php echo $this->escapeHtml($topic->topic_name); ?></td>
            <td><?php echo $this->escapeHtml($topic->topic_description); ?></td>
            <td>
                <a href="<?php echo $this->url('topic', array('action' => 'edit', 'topic_id' => $topic->topic_id));
        ?>">Edit</a> | <a href="<?php echo $this->url('topic', array('action' => 'delete', 'topic_id' => $topic->topic_id));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    <?php endif; ?>


    <?php if($this->paginator) : ?>
    <?php foreach ($paginator as $topic) :    
    ?>
        <tr>
            <td><?php echo $this->escapeHtml($topic->topic_name); ?></td>
            <td><?php echo $this->escapeHtml($topic->topic_description); ?></td>
            <td>
                <a href="<?php echo $this->url('topic', array('action' => 'edit', 'topic_id' => $topic->topic_id));
        ?>">Edit</a> | <a href="<?php echo $this->url('topic', array('action' => 'delete', 'topic_id' => $topic->topic_id));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    <?php endif; ?>
</table>
<?php
/*
    echo $this->paginationControl(
            $paginator, 'Sliding', 'paginator-slide', array('order_by' => $order_by, 'order' => $order,'search_by'=>$search_by)
    );
    */
    ?>