<?php
$title = 'Add / Edit New User';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url(NULL, array('controller'=>'users', 'action' => 'edit','user_id'=> $this->user_id)));
$form->setAttribute('class', "form-horizontal");
$form->setAttribute('role', "form");
$form->prepare();
?>
<h1 class="page-title"><?php echo $this->escapeHtml($title); ?></h1>
<div class="page-bar">
  <ul class="page-breadcrumb">
    <li><i class="fa fa-home"></i><a href="#">Home</a><i class="fa fa-angle-right"></i></li>
    <li><a href="<?php echo $this->url('manageuser',array('controller' => 'UserManager','action'=>'index')); ?>">User Management</a><i class="fa fa-angle-right"></i></li>
    <li><a href="<?php echo $this->url('manageuser',array('controller' => 'UserManager','action'=>'index')); ?>">Manage User</a><i class="fa fa-angle-right"></i></li>    
    <li>Add / Edit User</li>
  </ul>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="io-db-block">
      <div class="io-db-block-header">Add / Edit User</div>
       	<?php  echo $this->flashMessenger()->render('danger', array('alert', 'alert-danger'));    ?>
		<?php  echo $this->flashMessenger()->render('info', array('alert', 'alert-info'));        ?>
		<?php  echo $this->flashMessenger()->render('warning', array('alert', 'alert-warning'));  ?>
		<?php if($this->formElementErrors($form)) : ?>
            <div class="alert alert-danger">
                <?php echo $this->formElementErrors($form); ?>
            </div>
        <?php  endif; ?>
      <div class="io-db-block-content"> 
        <?php echo $this->form()->openTag($form); ?>          
          <div class="form-body">
            <div class="form-group">
              <label class="col-xs-12 col-md-3 control-label">First Name</label>  
              <div class="col-xs-12 col-md-5 col-lg-3">
                  <?php echo $this->formElement($form->get('fname')); ?>  
              </div>
            </div>

            <div class="form-group">
              <label class="col-xs-12 col-md-3 control-label">Last Name</label>  
              <div class="col-xs-12 col-md-5 col-lg-3">
                  <?php echo $this->formElement($form->get('lname')); ?>  
              </div>
            </div>
            <div class="form-group">
              <label class="col-xs-12 col-md-3 control-label">Email Address</label>  
              <div class="col-xs-12 col-md-5 col-lg-3">
                  <?php echo $this->formElement($form->get('email')); ?>  
              </div>
            </div>

            <div class="form-group">
              <label class="col-xs-12 col-md-3 control-label">Password</label>  
              <div class="col-xs-12 col-md-5 col-lg-3">
                  <?php echo $this->formElement($form->get('password')); ?>  
              </div>
            </div>
            <div class="form-group">
              <label class="col-xs-12 col-md-3 control-label">Confirm password</label>  
              <div class="col-xs-12 col-md-5 col-lg-3">
                  <?php echo $this->formElement($form->get('confirm_password')); ?>  
              </div>
            </div>
            <div class="form-group">
              <label class="col-xs-12 col-md-3 control-label">User Status</label>  
              <div class="col-xs-12 col-md-5 col-lg-3">
                  <?php echo $this->formElement($form->get('status')); ?>  
              </div>
            </div>
             <div class="form-group">
              <label class="col-xs-12 col-md-3 control-label">User Permission</label>  
              <div class="col-xs-12 col-md-5 col-lg-6">
                  <?php echo $this->formElement($form->get('permission')); ?>  
              </div>
            </div>
            <div class="form-actions">
              <div class="row">
                <div class="col-md-offset-3 col-md-9">                  
                  <button class="btn btn-io" type="submit">Update</button>
                  <!--<button class="btn btn-io" type="submit">Reset</button>-->
                  <button class="btn btn-io" onclick="javascript: window.history.back();" type="button">Back</button>
                </div>
              </div>
            </div>
          </div>
        <?php echo $this->form()->closeTag(); ?>
      </div>
    </div>
  </div>
</div>