<?php
$form = $this->form;
$form->setAttribute('class', "form-horizontal");
$form->setAttribute('role', "form");
$form->prepare();
?>

      <h1 class="page-title">Manage User</h1>
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li><i class="fa fa-home"></i><a href="#">Home</a><i class="fa fa-angle-right"></i></li>
          <li><a href="#">User Management</a><i class="fa fa-angle-right"></i></li>
          <li>Manage User</li>
        </ul>
      </div> 

      <div class="io-search-filter row">
        <div class="col-xs-6 col-sm-6">
          <?php  echo $this->flashMessenger()->render('danger', array('alert', 'alert-danger'));    ?>
          <?php  echo $this->flashMessenger()->render('info', array('alert', 'alert-info'));        ?>
          <?php  echo $this->flashMessenger()->render('warning', array('alert', 'alert-warning'));  ?>
          <h3>Search</h3>
        </div>      
        <div class="col-xs-6 col-sm-6 text-right">
          <a href="#collapseOne" data-parent="#accordion" data-toggle="collapse">Show / Hide</a></div>
         </div>
      
      <div id="collapseOne" class="io-filter-block panel-collapse collapse in">
        <?php echo $this->form()->openTag($form); ?> 
      	<div class="row">
        <div class="col-xs-12 col-sm-4 col-md-3">
            <label>Search Term</label>
            <?php echo $this->formElement($form->get('search')); ?>
            
        </div>      
        <div class="col-xs-12 col-sm-3 col-md-2">            
            <label>Select Status</label>            
            <?php echo $this->formElement($form->get('status')); ?>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-2">
          <label>&nbsp;</label>
          <div class="form-group">
            <button type="submit" class="btn btn-io">Search</button>
          </div>
        </div>
        </div>
         <?php echo $this->form()->closeTag(); ?>
      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 text-right">
          <?php if((int)$this->auth["client_id"]==0): ?>
                <a href="<?php echo $this->url('manageuser', array('controller'=>'users', 'action' => 'adduser')); ?>" class="btn btn-default">Add User</a>
            <?php endif; ?>          
        </div>
      </div>

      <div class="row mt-10">
        <div class="col-xs-12 col-sm-12">
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th class="text-center">S. No.</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Permission</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
              <?php if(count($this->paginator)==0) { ?>
                  <tr><td colspan ="6"><center><p>No record found<p></center></td></tr>
              <?php } ?>  
              <?php foreach ($this->paginator as $user) :   ?>
                        
                  <td class="text-center">1</td>
                  <td><?php echo $user->fname." ".$user->lname; ?></td>
                  <td><?php echo $user->email; ?></td>
                  <td>Human Resource</td>
                  <td><?php echo ($user->status==1)?"Active":"Inactive"; ?></td>
                  <td><ul class="quick-links">
                      <li><a href="<?php echo $this->url('manageuser', array('controller'=>'users', 'action' => 'edit','user_id'=> $user->user_id)); ?>"><i class="fa fa-edit"></i>Edit</a></li>
                      <li><a href="<?php echo $this->url('manageuser', array('controller'=>'users', 'action' => 'delete','user_id'=> $user->user_id)); ?>"><i class="fa fa-trash-o"></i>Delete</a></li>
                    </ul></td>
                </tr>
              <?php endforeach; ?>                
              </tbody>
            </table>
          </div>
             <?php // add at the end of the file after the table
                echo $this->paginationControl(
                      $this->topics,
                      'Sliding',
                      array('paginator.phtml', 'Topic'), 
                      array('route' => 'manageuser', 'query'=>($this->querydata!="")?"&{$this->querydata}":"")
                  );
                  
              ?> 
        </div>
      </div>
