      <h1 class="page-title">Manage User</h1>
      <div class="page-bar">
        <ul class="page-breadcrumb">
          <li><i class="fa fa-home"></i><a href="#">Home</a><i class="fa fa-angle-right"></i></li>
          <li><a href="#">User Management</a><i class="fa fa-angle-right"></i></li>
          <li>Manage User</li>
        </ul>
      </div>
      <div class="io-search-filter row">
        <div class="col-xs-6 col-sm-6">
          <h3>Search</h3>
        </div>
        <div class="col-xs-6 col-sm-6 text-right"><a href="#collapseOne" data-parent="#accordion" data-toggle="collapse">Show / Hide</a></div>
      </div>
      <div id="collapseOne" class="io-filter-block panel-collapse collapse in">
      	<div class="row">
        <div class="col-xs-12 col-sm-4 col-md-2">
            <label>Search Term</label>
            <input type="text" placeholder="Name / Email" id="" class="form-control">
        </div>
        <div class="col-xs-12 col-sm-3 col-md-2">
            <label>Select Role</label>
            <select class="form-control">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
        </div>
        <div class="col-xs-12 col-sm-3 col-md-2">
            <label>Select Status</label>
            <select class="form-control">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
        </div>
        <div class="col-xs-12 col-sm-2 col-md-2">
          <label>&nbsp;</label>
          <div class="form-group">
            <button type="submit" class="btn btn-io">Search</button>
          </div>
        </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12">
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th class="text-center">S. No.</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="text-center">1</td>
                  <td>Ashish Sharma</td>
                  <td>ashish.sharma@gmail.com</td>
                  <td>Human Resource</td>
                  <td>Active / Inactive</td>
                  <td><ul class="quick-links">
                      <li><a href="#"><i class="fa fa-edit"></i>Edit</a></li>
                      <li><a href="#"><i class="fa fa-trash-o"></i>Delete</a></li>
                    </ul></td>
                </tr>
                <tr>
                  <td class="text-center">2</td>
                  <td>Mukesh Bhardwaj</td>
                  <td>mukesh.bhardwaj@gmail.com</td>
                  <td>Finance</td>
                  <td>Active / Inactive</td>
                  <td><ul class="quick-links">
                      <li><a href="#"><i class="fa fa-edit"></i>Edit</a></li>
                      <li><a href="#"><i class="fa fa-trash-o"></i>Delete</a></li>
                    </ul></td>
                </tr>
                <tr>
                  <td class="text-center">3</td>
                  <td>Shailesh Shukla</td>
                  <td>shailesh.shukla2008@yahoo.com</td>
                  <td>Administration</td>
                  <td>Active / Inactive</td>
                  <td><ul class="quick-links">
                      <li><a href="#"><i class="fa fa-edit"></i>Edit</a></li>
                      <li><a href="#"><i class="fa fa-trash-o"></i>Delete</a></li>
                    </ul></td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="pagination-wrap">
            <ul class="pagination">
              <li class="disabled"><a href="#">«</a></li>
              <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#">»</a></li>
            </ul>
          </div>
        </div>
      </div>
