<div style="margin:15px 0 0 10px;overflow:visible;width:570px">
	<div class="adM"> </div>
		<h3 style="margin:0 0 8px 0;padding:0px">
				<span class="il">Password</span> reset</h3> 
				<div style="margin:6px 0 8px;padding:0;background-color:#333;min-height:4px;line-height:4px;font-size:4px">&nbsp;</div> 
				Dear #USERNAME#,<br><br>We received a request to reset your 
				<span class="il">password</span>. Please click here to reset the <span class="il">password</span> 
				#RESETLINK#
				<br><br>
				Sincerely,
				<br> Admin<br>				
				<div class="yj6qo"></div>
				<div class="adL"><br>
	</div>
</div>