<div style="margin:15px 0 0 10px;overflow:visible;width:570px">
	<div class="adM"> </div>
		<h3 style="margin:0 0 8px 0;padding:0px"></h3>			
				<div style="margin:6px 0 8px;padding:0;background-color:#333;min-height:4px;line-height:4px;font-size:4px">&nbsp;</div> 
				Hi #USERNAME#,<br><br>
				Thank you for signing up with Interview Organiser.<br /> 
				<span class="il"></span><a href="#CREATELINK#">Click Here to Activate Your Account</a>
				<br />
				<span class="il">#CREATELINK#</span><br /><br />
				Have questions, suggestions or feedback? We are here info@intervieworganiser.com
				<br><br>
				Thanks,
				<br> Team Interview Organiser<br>				
				<div class="yj6qo"></div>
				<div class="adL"><br>
	</div>
</div>