<?php

if ($this->pageCount): ?>
    <div class="pagination-centered">
        <ul class="pagination">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('topic', array('page' => $this->first, 'order_by' => $order_by, 'order' => $order,'search_by'=>$search_by)); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('topic', array('page' => $this->previous, 'order_by' => $order_by, 'order' => $order,'search_by'=>$search_by)); ?>">&lsaquo;</a></li>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('topic', array('page' => $page, 'order_by' => $order_by, 'order' => $order,'search_by'=>$search_by)); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo !isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('topic', array('page' => $this->next, 'order_by' => $order_by, 'order' => $order,'search_by'=>$search_by)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('topic', array( 'page' => $this->last, 'order_by' => $order_by, 'order' => $order,'search_by'=>$search_by)); ?>">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>