<!-- BEGIN SIDEBAR --> 
 <div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
      <ul class="page-sidebar-menu">
        <li class="sidebar-toggler-wrapper"> 
          <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
          <div class="sidebar-toggler"></div>
          <div class="clearfix"></div>
          <!-- BEGIN SIDEBAR TOGGLER BUTTON --> 
        </li>
        <li class=""> <a href="javascript:;"><i class="fa fa-users"></i><span class="title">User Management</span><span class="arrow"></span></a>
          <ul class="sub-menu">
            <li><a href="#"><i class="icon-anchor"></i>Manage User</a></li>
            <li><a href="#"><i class="icon-book-open"></i>Manage Role</a></li>
            <li><a href="#"><i class="icon-pin"></i>Change Password</a></li>
          </ul>
        </li>
        <li> <a href="javascript:;"><i class="fa fa-cubes"></i><span class="title">Component</span><span class="arrow"></span></a>
          <ul class="sub-menu">
            <li><a href="#"><i class="icon-anchor"></i>Manage Department</a></li>
            <li><a href="#"><i class="icon-book-open"></i>Manage Designation</a></li>
            <li><a href="#"><i class="icon-pin"></i>Manage Technologies</a></li>
            <li><a href="<?php echo $this->url('topic',array('controller' => 'ManageComponent','action'=>'index')); ?>"><i class="icon-pin"></i>Manage Topics</a></li>
          </ul>
        </li>
        <li> <a href="javascript:;"><i class="fa fa-question-circle"></i><span class="title">Question Bank</span><span class="arrow"></span></a>
          <ul class="sub-menu">
            <li><a href="#"><i class="icon-anchor"></i>Manage Question</a></li>
          </ul>
        </li>
        <li> <a href="javascript:;"><i class="fa fa-user"></i><span class="title">Interview</span><span class="arrow"></span></a>
          <ul class="sub-menu">
            <li><a href="#"><i class="icon-anchor"></i>Interview Sets</a></li>
            <li><a href="#"><i class="icon-book-open"></i>Scheduled Interview</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <!-- END SIDEBAR --> 