<div class="io-header"><img src="<?php echo $this->basePath('images/logo-io.png'); ?>" alt="Interview Organiser"></div>  
<div class="io-body">
<h3>Reset Password</h3>
<?php  echo $this->flashMessenger()->render('danger', array('alert', 'alert-danger')); ?>
<?php  echo $this->flashMessenger()->render('info', array('alert', 'alert-info')); ?>
<?php  echo $this->flashMessenger()->render('warning', array('alert', 'alert-warning')); ?>
<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url(NULL, array('controller'=>'users', 'action' => 'forget')));
	$form->setAttribute('method', 'post');
	echo $this->form()->openTag($form);?>
         

          <div class="form-group">
                <?php echo $this->formElement($form->get('email'));
                    echo $this->formElementErrors($form->get('email')); ?>
                <!-- <input type="email" placeholder="Email Address *" id="" class="form-control pl-20"> -->

              </div>       
          <!-- <button class="btn btn-io mt-10" type="submit">Login</button> -->
          <?php //echo $this->formElement($form->get('submit')); ?>
          <button class="btn btn-io  " type="submit">Send reset password link</button>
          <button class="btn btn-io " type="button" onclick="javascript: window.history.back();">Cancel</button>
          <div class="clearfix"></div>
<?php echo $this->form()->closeTag() ?>
</div>