<h2> New User Registration </h2>
<p> This page will hold the content for the registration form </p>

<section class="register">

<h2>Register</h2>
<?php if ($this->error): ?>
	<p class="error">
		There were one or more issues with your submission. Please correct them as indicated below.
	</p>
<?php endif ?>

<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url(NULL, array('controller'=>'users', 'action' => 'rgprocess')));
	$form->setAttribute('method', 'post');
	echo $this->form()->openTag($form);
?>

<dl class="zend_form">
	<dt><?php echo $this->formLabel($form->get('name')); ?></dt>
	<dd>
		<?php
			echo $this->formElement($form->get('name'));
			echo $this->formElementErrors($form->get('name'));
		?>
	</dd>
	<dt>
		<?php echo $this->formLabel($form->get('email')); ?>
	</dt>
	<dd>
		<?php
			echo $this->formElement($form->get('email'));
			echo $this->formElementErrors($form->get('email'));
		?>
	</dd>
	<dt>
		<?php echo $this->formLabel($form->get('password'));?>
	</dt>
	<dd>
		<?php
			echo $this->formElement($form->get('password'));
			echo $this->formElementErrors($form->get('password'));
		?>
	</dd>
	<!--<dt>
		<?php //echo $this->formLabel($form->get('confirm_password')); ?>
	</dt>
	<dd>
		<?php 
			//echo $this->formElement($form->get('confirm_password'));
			//echo $this->formElementErrors($form->get('confirm_password'));
		?>
	</dd>-->
	<dt>
		<?php echo $this->formLabel($form->get('address'));?>
	</dt>
	<dd>
		<?php
			echo $this->formElement($form->get('address'));
			echo $this->formElementErrors($form->get('address'));
		?>
	</dd>
	<dt>
		<?php echo $this->formLabel($form->get('phone')); ?>
	</dt>
	<dd>
		<?php 
			echo $this->formElement($form->get('phone'));
			echo $this->formElementErrors($form->get('phone'));
		?>
	</dd>
	<dd><br/></dd>
	<dd>
		<?php
			echo $this->formElement($form->get('submit'));
			echo $this->formElementErrors($form->get('submit'));
		?>
	</dd>
</dl>

<?php echo $this->form()->closeTag() ?>

</section>
<br/><br/>
<a href="/users"><< Back to Home</a>
