<div class="io-header"><img src="<?php echo $this->basePath('images/logo-io.png'); ?>" alt="Interview Organiser"></div>
<div class="io-body">
<h3>Welcome, create your account to get started.</h3>
<?php  echo $this->flashMessenger()->render('danger', array('alert', 'alert-danger'));    ?>
<?php  echo $this->flashMessenger()->render('info', array('alert', 'alert-info'));        ?>
<?php  echo $this->flashMessenger()->render('warning', array('alert', 'alert-warning'));  ?>

<?php if($this->formElementErrors($form)) : ?>
  <div class="alert alert-danger" role="alert">
    <?php echo $this->formElementErrors($form); ?>
  </div>
<?php  endif; ?>
<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url(NULL, array('controller'=>'users', 'action' => 'register')));
	$form->setAttribute('method', 'post');
	echo $this->form()->openTag($form);
?>
        <div class="row">
          <div class="col-xs-12 col-sm-6">
              <div class="form-group">
              	<?php echo $this->formElement($form->get('fname'));	 ?>
              </div>
              <div class="form-group">
              	<?php echo $this->formElement($form->get('lname')); ?>
              </div>
              <div class="form-group">
              	<?php echo $this->formElement($form->get('email')); ?>
              </div>
              <div class="io-form-note">Verification link will be sent to this Email ID.</div>
              <div class="form-group">
              	<?php echo $this->formElement($form->get('password')); ?>
              </div>
              <div class="form-group">
                <?php echo $this->formElement($form->get('confirm_password')); ?>
              </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
            	<?php echo $this->formElement($form->get('phone')); ?>
          </div>
            <div class="form-group">
            	<?php echo $this->formElement($form->get('organisation')); ?>
          </div>
            <div class="form-group">
            	<?php echo $this->formElement($form->get('designation')); ?>
          </div>
              <div class="form-group"><img alt="CAPTCHA Image" src="<?php echo $this->basePath('images/captcha.png'); ?>" id="captcha" class="captcha_image">&nbsp;&nbsp;<a href="#"><i class="fa fa-refresh"></i></a>
            <input type="text" placeholder="Type characters from the image *" id="" class="form-control mt-10 pl-20">
          </div>
            <button class="btn btn-io mt-10" type="submit">Sign Up</button>
          </div>
          </div>          
<?php echo $this->form()->closeTag() ?>
</div>