 <div class="io-header"><img src="<?php echo $this->basePath('images/logo-io-symbol.png'); ?>" alt="Interview Organiser"></div>
<div class="io-body">
<h3>Reset Password.</h3>
<?php if($this->formElementErrors($form)) : ?>
<div class="alert alert-danger" role="alert">
  <?php echo $this->formElementErrors($form); ?>
</div>
<?php  endif; ?>
<?php
	$form = $this->form;
	$form->prepare();
	//$form->setAttribute('action', $this->url(NULL, array('controller'=>'users', 'action' => 'reset')));
  $form->setAttribute('action', $this->url('users', array('action' => 'reset', 'param'     => $this->param)));
	$form->setAttribute('method', 'post');
	echo $this->form()->openTag($form);
?>
        <div class="row">
          <div class="col-xs-12 col-sm-6">              
              <div class="form-group">
              	<?php echo $this->formElement($form->get('password')); ?>                
              </div>
              <div class="form-group">
                <?php echo $this->formElement($form->get('confirm_password')); ?>                
              </div>
          </div>            
          </div>
            <button class="btn btn-io mt-10" type="submit">Reset Password</button>
          </div>
          </div>          
<?php echo $this->form()->closeTag() ?>
</div>